export const Users = [
    {
      id:1,
      profilePicture: "assests/pictures/1.png",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "assests/pictures/2.png",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assests/pictures/3.png",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assests/pictures/4.png",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assests/pictures/5.png",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assests/pictures/6.png",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assests/pictures/7.png",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assests/pictures/8.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assests/pictures/9.png",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assests/pictures/10.png",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assests/posts/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assests/posts/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assests/posts/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assests/posts/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assests/posts/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assests/posts/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assests/posts/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assests/posts/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assests/posts/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assests/posts/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];